 SMTP Configuration (Mailtrap)
smtp.host=sandbox.smtp.mailtrap.io
smtp.port=2525
smtp.username=c9406f6ca181ab
smtp.password=870364965e69b7



## SMTP Configuration (Gmail)
#smtp.host=smtp.gmail.com
#smtp.port=587
#smtp.username=bookr.project@gmail.com
#smtp.password=higt mubi oasp irjk


# Email Settings
email.from=noreply@bookr-project.hu
email.from.name=Bookr - Foglal\u00e1si Rendszer
email.enabled=true

# Application Base URL (for verification links)
app.base.url=http://localhost:8080/bookr